FlaskSocialCompanyBlog/esportscompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit = SubmitField("Create Post")

FlaskSocialCompanyBlog/esportscompanyblog/blog_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required

from esportscompanyblog import db
from esportscompanyblog.models.models import BlogPost
from esportscompanyblog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

# CREATE
@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash("Blog post created")
        return redirect(url_for('core.index'))
    return render_template('create_post.html', form=form)

# VIEW
@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post)


# UPDATE
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()


    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)


# DELETE
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))

FlaskSocialCompanyBlog/esportscompanyblog/core/views.py
from flask import render_template, request, Blueprint

from esportscompanyblog.models.models import BlogPost

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date).paginate(page=page, per_page=5)
    return render_template("index.html", blog_posts=blog_posts)

@core.route("/info")
def info():
    return render_template("info.html")

FlaskSocialCompanyBlog/esportscompanyblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from esportscompanyblog.models.models import User, BlogPost
from esportscompanyblog.users.forms import RegistrationForm, UpdateUserForm, LoginForm
from esportscompanyblog.users.picture_handler import add_profile_pic
from esportscompanyblog import db


users = Blueprint('users', __name__)

# register user
@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    # print("HERE", form.email.data, form.validate_on_submit(), form.errors, form.password.data, form.password_cmp.data)
    if form.validate_on_submit():
        # print("HERE 2")
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        print(user)
        db.session.add(user)
        db.session.commit()
        # user.create()
        flash("Thanks for registering!")
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# login view
@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_email(email=form.email.data)

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login Success!")

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))

# account (update userForm)
@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form =UpdateUserForm()

    print("Here", form.errors, form.validate_on_submit())

    if form.validate_on_submit():

        print(form.errors, form.picture.data)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
            print(current_user.profile_image)
        current_user.username = form.username.data
        current_user.email = form.email.data

        # current_user.update()
        db.session.commit()
        flash("User account updated!")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


# user's list of Blogs
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)

    user = User.get_by_username(username)
    # Because we set backref to author
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

FlaskSocialCompanyBlog/esportscompanyblog/templates/account.html
{% extends "base.html" %}

{% block content %}

<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-12 px-0">
        <h1 class="display-4 fst-italic">User Account</h1>
        <img align="center" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}" alt="Profile Image" />
    </div>

    <div class="container">
        <form method="POST" action="" enctype="multipart/form-data">

            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label(class='form-group') }} {{ form.username(class='form-control') }}
            </div>

            <div class="form-group">
                {{ form.email.label(class='form-group') }} {{ form.email(class='form-control') }}

            </div>
            <div class="form-group">
                {{ form.picture.label(class='form-group') }} {{ form.picture(class='form-control') }}
            </div>
            <div class="form-group">
                {{ form.submit(class='btn btn-primary') }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <title>Esports Blog</title>
</head>
<body>
    
    <ul class="nav">
        <li class="nav-link"><a href="{{ url_for('core.index')}}">Home</a></li>
        <li class="nav-link"><a href="{{ url_for('core.info')}}">About</a></li>

        {% if current_user.is_authenticated %}
            <li class="nav-link"><a href="{{ url_for('users.logout') }}">Log Out</a></li>
            <li class="nav-link"><a href="{{ url_for('users.account') }}">Account</a></li>
            <li class="nav-link"><a href="{{ url_for('blog_posts.create_post') }}">Create Post</a></li>
        {% else %}
            <li class="nav-link"><a href="{{ url_for('users.login') }}">Login</a></li>
            <li class="nav-link"><a href="{{ url_for('users.register') }}">Register</a></li>
        {% endif %}




    </ul>

    <div class="container">
        {% block content %}
    
        {% endblock %}
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

FlaskSocialCompanyBlog/esportscompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/index.html
{% extends "base.html" %}

{% block content %}
    
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Esports Blog</h1>
    </div>
</div>

    <div class="container">
    {% for post in blog_posts.items %}
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><a href="{{  url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h5>
              <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
            <p class="card-text">Published on: {{ post.date.strftime("%y-%m-%d") }}</p>
            <a href="{{  url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
          </div>
        </div>
    {% endfor %}


    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if blog_posts.page == page_num %}
                  <li class="page-item disabled">
                      <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% else %}
                  <li class="page-item">
                      <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endif %}
        {% endfor %}
      </ul>
    </nav>
{% endblock %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/info.html
{% extends "base.html" %}

{% block content %}
    
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-10 px-0">
        <h1 class="display-4 fst-italic">About Us</h1>
        <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
    </div>
</div>
{% endblock %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Login</h1>
    </div>
</div>

<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }} <br/>
    {{ form.password.label }} {{ form.password() }} <br />
    {{ form.submit() }}
</form>
{% endblock %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/register.html
{% extends "base.html" %}

{% block content %}
    
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Register a User</h1>
    </div>
</div>

<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }} <br/>
    {{ form.username.label }} {{ form.username() }} <br/>
    {{ form.password.label }} {{ form.password() }} <br />
    {{ form.password_cmp.label }} {{ form.password_cmp() }} <br />
    {{ form.submit() }}
</form>
{% endblock %}

FlaskSocialCompanyBlog/esportscompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
            <div class="col-md-12 px-0">
                <h1 class="display-4 fst-italic">Welcome to the page for {{ user.username }}</h1>
                <img align="center" src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}" alt="Profile Image" />
            </div>
        </div>

    {% for post  in blog_posts.items %}
        <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        Written by: <a href="{{  url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <p class="text-muted">Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
        <p>{{ post.text }}</p>
        <br>

    {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if blog_posts.page == page_num %}
                  <li class="page-item disabled">
                      <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% else %}
                  <li class="page-item">
                      <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endif %}
        {% endfor %}
      </ul>
    </nav>


{% endblock %}